namespace: prometheus
resources:
- namespace.yml
- rbac.yml
- pvc.yml
- ingress.yml
- svc.yml
- be-deploy.yml
- be-svc.yml
- kube-state-metrics.yml
- prometheus.yml
- alertmanager.yml
- grafana.yml
- karma.yml
- node-exporter-ds.yml
#- telegram-bot-sealed.yml
#- telegram-bot.yml

configMapGenerator:
- name: prometheus-config
  files:
  - prometheus.yml=prometheus-config.yml
- name: prometheus-rules
  files:
  #- rules/etcd.yml
  #- rules/kube-state-metrics.yml
  - rules/node-exporter.yml
  - rules/prometheus.yml
- name: grafana-config
  files:
  - grafana.ini=grafana-config.ini
  - datasources.yml=grafana-datasources.yml
  - dashboards.yml=grafana-dashboards.yml
- name: karma-config
  files:
  - config.yml=karma-config.yml
- name: alertmanager-config
  files:
  - config.yml=alertmanager-config.yml
- name: grafana-dashboards
  files:
  - 1860.json=grafana-dashboard-1860-min.json
  #- kubernetes-mixin/dashboards_out/apiserver.json
  #- kubernetes-mixin/dashboards_out/cluster-total.json
  #- kubernetes-mixin/dashboards_out/controller-manager.json
  #- kubernetes-mixin/dashboards_out/k8s-resources-cluster.json
  #- kubernetes-mixin/dashboards_out/k8s-resources-namespace.json
  #- kubernetes-mixin/dashboards_out/k8s-resources-node.json
  #- kubernetes-mixin/dashboards_out/k8s-resources-pod.json
  #- kubernetes-mixin/dashboards_out/k8s-resources-workload.json
  #- kubernetes-mixin/dashboards_out/k8s-resources-workloads-namespace.json
  #- kubernetes-mixin/dashboards_out/kubelet.json
  #- kubernetes-mixin/dashboards_out/namespace-by-pod.json
  #- kubernetes-mixin/dashboards_out/namespace-by-workload.json
  #- kubernetes-mixin/dashboards_out/persistentvolumesusage.json
  #- kubernetes-mixin/dashboards_out/pod-total.json
  #- kubernetes-mixin/dashboards_out/proxy.json
  #- kubernetes-mixin/dashboards_out/scheduler.json
  #- kubernetes-mixin/dashboards_out/statefulset.json
  #- kubernetes-mixin/dashboards_out/workload-total.json
- name: be-config
  files:
  - config.yml=be-config.yml
generatorOptions:
  disableNameSuffixHash: false
  labels:
    generator: kustomize
#images:
#- name: karma
#  newTag: v0.78
